version: '3.9'

services:
  
  grafana:
    container_name: grafana
    image: grafana/grafana:5.4.3
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana

  nodeapp:
    container_name: nodeapp
    image: francescoxx/social-dashboard:nodeapp-0.0.2
    build:
      context: js
    ports:
      - '8080:8080'
    environment:
      - EXTERNALPORT=8080
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=db
      - GITHUB_USERNAME=FrancescoXX
      - TWITTER_USERNAME=FrancescoCiull4
      - HASHNODE_USERNAME=FrancescoCiulla
      - INSTAGRAM_USERNAME=francescociullaroma
      - YOUTUBE_CHANNEL_ID=UCBRxDSTfr2aJVODDh4WG_7g
      - TWITCH_USER_ID=467501393
    env_file:
      - .env 

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
  grafana-storage: {}