version: '3.9'

services:
  
  grafana:
    container_name: grafana
    image: grafana/grafana:5.4.3
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana

  nodeapp:
    container_name: nodeapp
    image: social-dashboard:nodeapp-0.0.1
    build:
      context: js
    ports:
      - '8080:8080'
    environment:
      - EXTERNALPORT=8080
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=db
      - GITHUB_USERNAME=saminacodes # your github username
      - TWITTER_USERNAME=saminacodes # your twitter username
    env_file:
      - .env 


  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
  grafana-storage: {}